- name: xe automation
  
  vars:
    login: &login
      host: '{{ ansible_host }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'

  block: 
  
  - name: Configure device
    ios_config:
      <<: *login
      lines: '{{command}}'
